version: '3.6'

services:
  groupbutler:
    environment:
      - GB_ADMIN_MODE
      - GB_CACHE_ADMIN
      - GB_OLD_UPDATE
      - GB_CHANNEL
      - GB_SOURCE
      - DEFAULT_LANG
      - HELP_GROUP
      - LOG_CHAT
      - LOG_ADMIN
      - LOG_STATS
      - MULTIPURPOSE_PLUGINS
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - SUPERADMINS
      - TG_TOKEN
      - TG_UPDATES
      - TG_POLLING_LIMIT
      - TG_POLLING_TIMEOUT
      - TG_WEBHOOK_URL
      - TG_WEBHOOK_DOMAIN
      - TG_WEBHOOK_CERT
      - TG_WEBHOOK_MAX_CON
    image: ${IMAGE:-groupbutler/groupbutler}:${TAG:-latest}
